name: Validate ok-to-test label

on:
  pull_request_target:
    # SAFETY: Jobs MUST NOT check out code.
    types: [synchronize]

jobs:
  remove-label-if-needed:
    runs-on: ubuntu-22.04
    permissions:
      # SAFETY: Only enough to modify labels.
      issues: write
    steps:
      - name: Remove ok-to-test label on push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          FULL_REPO: ${{ github.event.repository.full_name }}
        run: |
          permission="$(gh api "repos/${FULL_REPO}/collaborators/${PR_AUTHOR}/permission" --jq '.permission')"
          echo "User ${PR_AUTHOR} has permission '${permission}'"

          if [[ "${permission}" != "write" && "${permission}" != "admin" ]]; then
            echo "Removing 'ok-to-test' label"
            gh pr edit "${PR_NUMBER}" --repo "${FULL_REPO}" --remove-label "ok-to-test"
          else
            echo "User has label permission - skipping removal"
          fi
